### ISSUE TITLE
Script should provide more output to the user about what's happening

### ISSUE THREAD

**Issue by tmilliman** [khufkens/phenocam-installation-tool#13]
From Andrew:

It occurs to me… for the PIT, it would be very useful to spit back to the user a bit more information at the end. “Test image upload completed successfully. Camera set to upload between X am and Y pm at an interval of Z minutes, starting at A minutes past the hour. FTP set to active (passive) mode.”

**Comment by khufkens** [comment]
Fixed by @tmilliman, thanks
