### ISSUE TITLE
NTP server configuration

### ISSUE THREAD

**Issue by tmilliman** [khufkens/phenocam-installation-tool#16]
The choice of time.nist.gov may not work well outside of the US.  I'm wondering if using pool.ntp.org might be a better choice.  There is much discussion of this issue on the net and my sense is that for the accuracy we require using pool.ntp.org would be a better choice.

**Comment by khufkens** [comment]
I've changed this but did not confirm if this worked. You should ask @bnasr to update the file on the server and see if time still tracks.

**Comment by khufkens** [comment]
Confirmed to work, integrated in new version.
