### ISSUE TITLE
Server mismatch

### ISSUE THREAD

**Issue by patricktokeeffe** [khufkens/phenocam-installation-tool#9]
Installation occurs via a recursive mechanism, but the name of the server hosting the source code archive (`phenocam.sr.unh.edu`) is not the same as the server the installed scripts point to (`klima.sr.unh.edu`). This prevents users from re-running the installation script on the device itself, which impairs development.

*Relevant stdout excerpt:*
````bash
#--------------------------------------------------------------------
#
# Downloading settings from klima.sr.unh.edu !
#
#--------------------------------------------------------------------

wget: not an http or ftp url: klima.sr.unh.edu/data/configs/phenocam_default_install.tar.gz
gunzip: phenocam_default_install.tar.gz: Invalid argument
tar: Error opening 'phenocam_default_install.tar': No such file or directory
rm: cannot remove `phenocam_default_install.tar': No such file or directory
cat: default_overlay0.conf: Invalid argument
cat: default_ftp.scr: Invalid argument
cat: default_IR_ftp.scr: Invalid argument
cat: default_IP_ftp.scr: Invalid argument
cat: default_video0.conf: Invalid argument
cat: default_ntp.server: Invalid argument
cat: default_sched0.conf: Invalid argument
rm: cannot remove `default_*': No such file or directory
ln: /var/httpd/metadata.cgi: File exists
ln: /var/httpd/rgb.cgi: File exists
````

Perhaps the source code archive host should be hard-coded instead of using `$HOST` (the image storage server) [[line ref](https://github.com/khufkens/phenocam-installation-tool/blob/master/files/phenocam_install.sh#L180)]: 
```sh
# remove previous install files
if [ -f phenocam_default_install.tar* ]; then
	rm phenocam_default_install.tar*
fi

# download the installation files from the PhenoCam servers
wget $HOST/data/configs/phenocam_default_install.tar.gz

gunzip phenocam_default_install.tar.gz
tar -xvf phenocam_default_install.tar
rm phenocam_default_install.tar

fi
```

**Comment by khufkens** [comment]
The traffic should be redirected but I've had issues with wget on the cameras not playing nice with these kind of things. It works in a normal terminal but often doesn't on the camera. I'll rename the $HOST to phenocam.sr.unh.edu and add http://, this should resolve things.

### klima trace
---
wget http://klima.sr.unh.edu/data/configs/phenocam_default_install.tar.gz
--2017-09-02 20:21:23--  http://klima.sr.unh.edu/data/configs/phenocam_default_install.tar.gz
Resolving klima.sr.unh.edu... 132.177.243.160, 2606:4100:38a0:243::160
Connecting to klima.sr.unh.edu|132.177.243.160|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://phenocam.sr.unh.edu/data/configs/phenocam_default_install.tar.gz [following]
--2017-09-02 20:21:23--  http://phenocam.sr.unh.edu/data/configs/phenocam_default_install.tar.gz
Resolving phenocam.sr.unh.edu... 132.177.243.160, 2606:4100:38a0:243::160
Reusing existing connection to klima.sr.unh.edu:80.
HTTP request sent, awaiting response... 200 OK
Length: 7849 (7.7K) [application/octet-stream]
